### ISSUE TITLE
If stratumUser is not a bitcoin address, grafana stats go under regtest i.o. mainnet

### ISSUE THREAD

**Issue by jomz** [shufps/piaxe-miner#20]
If stratumUser is not a btc address type, self.network is set to regtest:

https://github.com/shufps/piaxe-miner/blob/master/shared/shared.py#L308-L316

and because of that, influx logs to regtest rather than mainnet:

https://github.com/shufps/piaxe-miner/blob/47e3ef9eded43b6764e9cf053406cd547366296a/piaxe/miner.py#L199

**Comment by shufps** [comment]
fixed #21
